default_platform(:ios)

def steps_1  
  sh("flutter clean")
  increment_build_number(
    build_number: latest_testflight_build_number + 1,
  xcodeproj: "Runner.xcodeproj"
  )    
  increment_version_number(
  bump_type: "minor",
  version_number: "0.1.4",
  xcodeproj: "Runner.xcodeproj"
  )
  sh("flutter pub get")
end

def steps_2
  get_certificates
    get_provisioning_profile
    build_app(workspace: “Runner.xcworkspace”, scheme: “Runner”)
    upload_to_testflight(
      skip_waiting_for_build_processing: true
    )
end

platform :ios do
  desc “Push a new production build to TestFlight”
  lane :testflight_lane do
    steps_1
    sh('flutter build ios --release --no-codesign')
    steps_2
  end
end