name: wholesaler_partner
version: 0.1.8+12
#version: 0.1.11
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  cached_network_image: ^3.2.1
  carousel_slider: ^4.0.0
  change_app_package_name: ^1.1.0
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  dotted_border: ^2.0.0+2
  dropdown_search: ^5.0.3
  firebase_core: ^2.4.0
  firebase_messaging: ^14.1.4
  firebase_core_platform_interface: ^4.5.2
  flutter:
    sdk: flutter
  flutter_datetime_picker: ^1.5.1
  flutter_launcher_icons: ^0.9.2
  flutter_local_notifications: ^9.7.0
  firebase_analytics: ^10.0.7
  flutter_localizations:
    sdk: flutter
  font_awesome_flutter: ^10.1.0
  freezed_annotation: ^2.2.0
  get: ^4.6.1
  get_storage: ^2.0.3
  html_editor_enhanced: ^2.5.0
  image_picker: ^0.8.4+9
  intl: ^0.17.0
  modal_bottom_sheet: ^2.0.0
  # month_picker_dialog: ^0.4.0
  month_picker_dialog:
    git:
      url: https://github.com/coolbootscoder/month_picker_dialog.git
  month_year_picker: ^0.2.0+1
  package_info_plus: ^1.4.0
  percent_indicator: ^4.0.0
  syncfusion_flutter_calendar: ^19.4.47
  url_launcher: ^6.1.2
  webview_flutter: ^3.0.4
  wholesaler_user:
    path: ../wholesaler-user

dev_dependencies:
  build_runner: null
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.2.1
  json_serializable: null
  lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/SpoqaHanSansNeo/
    - assets/shared_images_icons/

  fonts:
    - family: SpoqaHanSansNeo-Medium
      fonts:
        - asset: assets/fonts/SpoqaHanSansNeo/SpoqaHanSansNeo-Medium.ttf

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/shared_images_icons/partner_logo.jpg"
