name: wholesaler_user
description: A new Flutter project.
publish_to: "none"
version: 0.1.7+161
#version: 0.1.10

environment:
  sdk: ">=2.17.0 <3.0.0"
dependencies:
  cached_network_image: ^3.2.1
  carousel_slider: ^4.0.0
  cross_scroll: ^0.0.75
  firebase_core: ^2.4.0
  firebase_messaging: ^14.1.4
  flutter:
    sdk: flutter
  flutter_inappwebview: ^5.7.1
  flutter_launcher_icons: ^0.9.2
  flutter_local_notifications: ^9.7.0
  flutter_native_timezone: ^2.0.0
  flutter_rating_bar: ^4.0.0
  font_awesome_flutter: ^10.1.0
  get: ^4.6.5
  get_storage: ^2.0.3
  iamport_flutter: ^0.10.1+3
  infinite_scroll_pagination: ^3.1.0
  intl: ^0.17.0
  kpostal: ^0.5.1
  package_info_plus: ^1.4.0
  path_provider: ^2.0.11
  smooth_page_indicator: ^1.0.0+2
  syncfusion_flutter_datepicker: ^19.4.56
  webview_flutter: ^3.0.4
  firebase_analytics: ^10.0.7
  wholesaler_partner:
    path: ../wholesaler-partner

dev_dependencies:
  change_app_package_name: ^1.1.0
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/shared_images_icons/
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/shared_images_icons/logo.jpeg"
