// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaRnvK3vm3M1fLvUl2RewIHok3H9t5yMk',
    appId: '1:463888941632:web:febe8daca32fd6da5dd5a5',
    messagingSenderId: '463888941632',
    projectId: 'thinkshow-71d1d',
    authDomain: 'thinkshow-71d1d.firebaseapp.com',
    storageBucket: 'thinkshow-71d1d.appspot.com',
    measurementId: 'G-GVBV6P8BCF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfH1ij1hmNNxXpDhiM5J-xVLcrQB2c1gI',
    appId: '1:463888941632:android:d591a1374a49f6fa5dd5a5',
    messagingSenderId: '463888941632',
    projectId: 'thinkshow-71d1d',
    storageBucket: 'thinkshow-71d1d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDW_db3mDXDsoDnum6IincQLMdlwdNaY5I',
    appId: '1:463888941632:ios:4b3422658937e6385dd5a5',
    messagingSenderId: '463888941632',
    projectId: 'thinkshow-71d1d',
    storageBucket: 'thinkshow-71d1d.appspot.com',
    iosClientId: '463888941632-110009nq7p6cectbick4and23dtdo4ah.apps.googleusercontent.com',
    iosBundleId: 'com.thinksmk.user',
  );
}
