import 'package:get/get.dart';

class pLanguages extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'ko_KR': {
          'save': '저장',
          'by_sales': '판매순',
          'move': '이동',
          'top': '맨위',
          'auto_register_product': '추천상품 자동등록',
          'everyday_from_00_00_until_23_59': '매일 00:00시 부터 23:59 까지 집계된 내역입니다.',
          'order': '주문',
          'like': '찜',
          'click': '클릭',
          'impression': '노출',
          'number_of_orders': '주문수',
          'Wholesale_report': '도매리포트',
          'business_register_image_deleted': '사업자등록증 사진 삭제 되었습니다.',
          'business_register_image': '사업자등록 이미지.jpg',
          'upload_business_registration_file': '사업자등록증을 업로드해주세요.',
          'Email_inquiry': 'Email 문의하기',
          'sign_up': '가입하기',
          'privacy_policy': '개인정보취급방침',
          'Accept_terms': '이용약관 동의',
          'agree_all': '모두 동의',
          'input_verification_num': '인증번호 입력',
          'verify': '인증',
          'phone_number': '휴대폰 번호',
          'signup_ceo': '회원가입 대표',
          'business_register_register': '사업자등록증 등록',
          'business_register_number': '사업자 번호',
          'check_availability': '중복확인',
          'id': '아이디',
          'CEO_name': '대표자 이름',
          'next': '다음',
          // 'search_by_company_name': '상호명으로 검색해보세요.',
          // 'company_name': '상호명',
          'appartment_number': '호수',
          'building_floor': '건물 층',
          'building': '건물',
          // 'staff': '직원',
          'CEO': '대표',
          'SignUp': '회원가입',
          'registration_failed': '가입 실패되었습니다.',
          'successfully_registered': '정상적으로 가입 완료되었습니다.',
          'accept_both_terms_and_privacy': '이용약관 및 개인정보취급방침을 모두 동의하세요.',
          'verify_your_mobile_phone_number.': '휴대폰번호를 인증 하세요.',
          'select_lake.': '호수를 선택해주세요.',
          'select_building_floor.': '건물 층을 선택해주세요.',
          // 'select_building.': '건물을 선택해주세요.',
          // 'Select_All': '전체선택',
          'dingdong': '띵동',
          'Register_dingdong_product': '띵동 상품으로 등록',
          'restock': '재입고',
          'Soldout': '품절',
          // 'Apply_filter': '필터 적용',
          'Period_inquiry': '기간조회',
          '3month': '3개월',
          '1month': '1개월',
          'day': '당일',
          'there_is_no_response': '아직까지 답변이 없습니다.',
          'manager': '관리자',
          'Sum': '합계',
          'etc': '기타',
          'fees': '마진',
          'return': '반품',
          'purchase_confirmation': '구매확정',
          'sales_price': '판매금액',
          'VAT_included': '(VAT포함입금)',
          'payment_amount': '정산 금액',
          'quantity': '수량',
          'option': '옵션',
          'item': '품목',
          'payment_history': '정산내역',
          'sales_history': '판매내역',
          'logout': '로그아웃',
          'privacy_terms': '이용약관 & 개인정보취급방침',
          'review': '리뷰',
          'product_inquiry': '상품문의',
          // 'our_store_top10': '우리매장 TOP10',
          'verify_business_register_doc': '사업자등록증 확인',
          'manage_my_bank': '내 계좌번호 관리',
          'settlement': '정산',
          'shopping_ed': '쇼핑에드',
          'advertising_center': '광고센터',
          'CEO': '대표',
          'employee': '직원',
          'edit': '수정하기',
          'password_verify': '비밀번호 확인',
          'password': '비밀번호',
          'manage_my_info': '내 정보 관리',
          'order_price': '주문금액',
          'Delivery_completed': '전달완료',
          'Packing_completed': '포장완료',
          'order_completed': '주문완료',
          'Product_Name_Search': '상품명 검색',
          'All_products': '전체상품',
          'Settlement_mgmt': '정산관리',
          'manage': '관리하기',
          'our_store_best': '우리매장 베스트',
          'View_more': '더보기',
          // 'edit_top_banner': '상단배너 수정',
          'register_top_banner': '상단배너 등록',
          // 'sales_mgmt': '매출관리',
          // 'product_mgmt': '상품관리',
          'register': '등록하기',
          'account_number': '계좌번호 입력',
          'account_holder': '예금주 입력',
          'select_bank': '은행선택',
          // 'register_my_bank': '내 계좌번호 등록',
          'delete': '삭제',
          'management': '관리',
          'approve': '승인',
          'rank': '직급',
          'name': '이름',
          'install_app': '앱설치',
          'staff_register_approve': '직원가입 및 승인 방법',
          // 'latest_number': '최신수',
          // 'dingdong_delivery': '띵동 배송',
          'customer_center': '고객센터',
          'close': '닫기',
          'business_registration_image_edit': '사업자 등록증 사진 변경',
          'business_registration_image_upload': '사업자 등록증 사진 등록',
          'Sample': '샘플',
          'ad_center_required_docs': '광고 센터 이용필수 서류 안내',
          // 'staff_management': '직원관리',
          'image_uploaded': '사진 정상적으로 업로드 되었습니다.',
          'ok': '획인',
          // 'ddi_you_complete_product_registration': '상품 등록을 완료하시겠습니까?',
          'you_want_exit_product_registration_screen':
              '상품등록중입니다. 상품등록화면에서 나가시겠습니까?',
          'Register_product': '상품등록하기',
          'go_back': '뒤로가기',
          'Country_manufacture_required': '제조국 표기 ( 필수 )',
          'Direct_input': '직접입력',
          'china': '중국',
          'korea': '대한민국',
          'size': '사이즈',
          'weight': '몸무게',
          'height_2': '키',
          'model_information': '모델정보',
          'Material_selection': '소재선택',
          'Garment_Care_Guide': '의류 관리 안내',
          'lining': '안감',
          'elasticity': '신축성',
          'see_through': '비침',
          'thickness': '두께감',
          'mix_ratio_input': '혼용률 입력',
          'washing_machine_ban': '세탁기 금지',
          'No_ironing': '다림질 금지',
          'No_bleach': '표백제 사용 금지',
          'wool_laundry': '울세탁',
          'single_laundry': '단독세탁',
          'washing_in_water': '물세탁',
          'dry_cleaning': '드라이클리닝',
          'hand_wash': '손세탁',
          'included': '있음',
          'banding': '밴딩',
          'not_included': '없음',
          'height': '높음',
          'thin': '얇음',
          'middle': '중간',
          'thick': '두꺼움',
          'Price': '금액',
          // 'Option_unit_price_registration': '옵션 단가등록',
          'Enter_option': '옵션 입력',
          'arm_section': '총기장',
          'bottom_section': '밑단단면',
          'thigh_section': '허벅지단면',
          'cross_section': '밑위단면',
          'hip_section': '엉덩이단면',
          'waist_section': '허리단면',
          // 'Product_registration': '상품등록',
          'dingdongDelivery': '띵동배송',
          'Product_photo_registration': '상품 사진 등록',
          'enter_color': '색상을 입력해주세요.',
          'enter_keywords': '키워드를 입력해주세요.',
          'unit_price': '단가',
          'enter_product_name': '상품명을 입력해주세요( 1 ~40자 )',
          'detail_cut': '디테일 컷',
          'image_by_color': '색상별 이미지',
          'representative_image': '대표이미지',
          'advertising_area_R': '광고 영역 (R)',
          'total_advertising_cost': '총 광고비용',
          'purchase_conversion_rate': '구매전환률',
          'number_of_likes': '찜수',
          'ad_cost': '광고비',
          'number_of_purchases': '구매수',
          'click_rate': '클릭률',
          'clicks': '클릭수',
          'impressions': '노출수',
          'advertising_performance': '광고 성과',
          'Point_usage_history': '포인트 사용내역서',
          'charging': '충전',
          'Application_history': '신청내역',
          'Advertising_Status': '광고현황',
          'ad_apply': '광고신청',
          'Payment_completion_amount': '결제완료 금액',
          'Expected_payment_amount': '결제예정 금액',
          'pay': '결제하기',
          'Advertising_R_Application_History': '쇼띵 광고 R 신청 내역',
          'Apply': '신청하기',
          '1_day_24': '1일 기준 (24시)',
          'Ad_Position_Description': '광고 위치 설명위치 설명위치 설명',
          // 'register_your_product': '상품을 등록해주세요',
          'ad_r': '광고 R',
          // 'ad_impression': '노출광고',
          'dingdong_order_price': '띵동 주문 금액',
          'order_amount': '주문 금액',
          'store_visits': '매장 방문수',
          'Product_change': '상품변경',
          'Ad_registration': '광고등록',
          'cancel': '취소',
          'When_the_daily_budge':
              '-일간 예산이 모두 소진되면 광고가 자동 중단되고 다음날 다시 정상 노출 됩니다. \n\n-경우에따라 예산 초과 금액이 발생 될 수 있습니다',
          'won': '원',
          'daily_budget': '일간예산',
          // 'remaining_points': '잔여 포인트',
          'ad': '광고',
          'bulletin': '공지사항',
          'its_bulletin': '공지사항입니다',
          'phone_verification_failed': '휴대폰 인증 실패. 다시 인증하세요.',
          'phone_verification_finished': '휴대폰 인증이 완료되었습니다.',
          'sent_verification_number': '인증번호를 발송했습니다.',
          'home': '홈',
          'orderHistory': '주문내역',
          'myPage': '마이페이지',
        },
        'en_US': {
          'save': 'save',
          'by_sales': 'by sales',
          'move': 'move',
          'top': 'top',
          // 'manual_register_product': 'Manual Add product',
          'auto_register_product': 'Auto Add product',
          'everyday_from_00_00_until_23_59':
              'It is the aggregated history from 00:00 to 23:59 every day.',
          'order': 'order',
          'like': 'like',
          'click': 'click',
          'impression': 'impression',
          'number_of_orders': 'number of orders',
          'Wholesale_report': 'Wholesale report',
          'business_register_image_deleted':
              'business registration certificate image deleted.',
          'business_register_image': 'Business registration image.jpg',
          'upload_business_registration_file':
              'Please upload your business registration file.',
          'Email_inquiry': 'Email inquiry',
          'sign_up': 'sign up',
          'privacy_policy': 'Privacy policy',
          'Accept_terms': 'Accept the terms and conditions',
          'agree_all': 'Agree to all',
          'input_verification_num': 'Input verification number.',
          'verify': 'verify',
          'phone_number': 'Phone Number',
          'signup_ceo': 'Sign up CEO',
          'business_register_register': 'Submit Business registration doc',
          'business_register_number': 'business register number',
          'check_availability': 'check availability',
          'id': 'id',
          'CEO_name': 'CEO Name',
          'next': 'next',
          'search_by_company_name': 'Search by business name.',
          'company_name': 'business name',
          'appartment_number': 'appartment number',
          'building_floor': 'building floor',
          'building': 'building',
          'staff': 'employee',
          'CEO': 'CEO',
          'SignUp': 'Sign Up',
          'registration_failed': 'Signup failed.',
          'successfully_registered': 'You have successfully signed up.',
          'accept_both_terms_and_privacy':
              'Agree to all terms of use and privacy policy.',
          'verify_your_mobile_phone_number.':
              'Please verify your mobile phone number.',
          'select_lake.': 'Please select appartment number.',
          'select_building_floor.': 'Please select a building floor.',
          'select_building.': 'Please select a building.',
          'Select_All': 'Select All',
          'dingdong': 'Dingdong',
          'Register_dingdong_product': 'Register as a Dingdong product',
          'restock': 'restock',
          'Soldout': 'Sold out',
          'Apply_filter': 'Apply filter',
          'Period_inquiry': 'Period inquiry',
          '3month': '3 months',
          '1month': '1 month',
          'day': 'day',
          'there_is_no_response': 'No answer yet.',
          'manager': 'manager',
          'Sum': 'Sum',
          'etc': 'etc',
          'fees': 'fees',
          'return': 'return',
          'purchase_confirmation': 'purchase confirmation',
          'sales_price': 'sale price',
          'VAT_included': '(VAT included)',
          'payment_amount': 'payment amount',
          'quantity': 'Quantity',
          'option': 'option',
          'item': 'item',
          'payment_history': 'payment history',
          'sales_history': 'Sales history',
          'logout': 'Log out',
          'privacy_terms': 'Terms of service',
          'review': 'review',
          'product_inquiry': 'Product Inquiry',
          // 'our_store_top10': 'TOP10 of our store',
          'verify_business_register_doc': 'Business registration confirmation',
          'manage_my_bank': 'Manage my account number',
          'settlement': 'payment',
          'shopping_ed': 'shopping ed',
          'advertising_center': 'ad center',
          'CEO': 'ceo',
          'employee': 'employee',
          'edit': 'edit',
          'password_verify': 'verify password',
          'password': 'password',
          'manage_my_info': 'my info',
          'order_price': 'order amount',
          'Delivery_completed': 'Delivery complete',
          'Packing_completed': 'Packing complete',
          'order_completed': 'order complete',
          'Product_Name_Search': 'Product Name Search',
          'All_products': 'All products',
          'settlement_amount': 'payment amount',
          'Settlement_mgmt': 'payment management',
          'manage': 'manage',
          'our_store_best': 'Best in our store',
          'View_more': 'View more',
          'edit_top_banner': 'edit top banner',
          'register_top_banner': 'top banner register',
          'sales_mgmt': 'Sales mgmt',
          'product_mgmt': 'product mgmt',
          'register': 'registr',
          'account_number': 'Enter account number',
          'account_holder': 'Enter account holder name',
          'select_bank': 'select bank',
          'register_my_bank': 'Register my account number',
          'delete': 'delete',
          'management': 'manage',
          'approve': 'Approve',
          'rank': 'rank',
          'name': 'name',
          'install_app': 'app installation',
          'staff_register_approve': 'sign up and approve employees',
          'latest_number': 'latest',
          'dingdong_delivery': 'Dingdong delivery',
          'customer_center': 'Service center',
          'close': 'close',
          'business_registration_image_edit':
              'Change the business license photo',
          'business_registration_image_upload':
              'Business registration photo registration',
          'Sample': 'Sample',
          'ad_center_required_docs':
              'Information on required documents for use of the advertising center',
          'staff_management': 'staff management',
          'image_uploaded': 'The photo has been successfully uploaded.',
          'ok': 'ok',
          'ddi_you_complete_product_registration':
              'Are you sure you want to complete product registration?',
          'you_want_exit_product_registration_screen':
              'Product is not yet registered. Are you sure you want to exit the product registration screen?',
          'Register_product': 'Register product',
          'go_back': 'go back',
          'Country_manufacture_required': 'Country of manufacture (required)',
          'Direct_input': 'Direct input',
          'china': 'china',
          'korea': 'Korea',
          'size': 'size',
          'weight': 'weight',
          'height_2': 'height',
          'model_information': 'model information',
          'Material_selection': 'Material selection',
          'Garment_Care_Guide': 'Garment Care Guide',
          'lining': 'lining',
          'elasticity': 'elasticity',
          'see_through': 'see through',
          'thickness': 'thickness',
          'mix_ratio_input': 'mix ratio input',
          'washing_machine_ban': 'No washing machine',
          'No_ironing': 'No ironing',
          'No_bleach': 'No bleach',
          'wool_laundry': 'wool laundry',
          'single_laundry': 'single laundry',
          'washing_in_water': 'washing in water',
          'dry_cleaning': 'dry cleaning',
          'hand_wash': 'hand wash',
          'included': 'included',
          'banding': 'banding',
          'not_included': 'not included',
          'height': 'height',
          'thin': 'thin',
          'middle': 'middle',
          'thick': 'thick',
          'Price': 'Price',
          'Enter_option': 'Enter option',
          'arm_section': 'arm section',
          'bottom_section': 'bottom section',
          'thigh_section': 'thigh section',
          'cross_section': 'cross section',
          'hip_section': 'hip section',
          'waist_section': 'waist section',
          'Product_registration': 'Product regist.',
          'dingdongDelivery': 'Dingdong Shipping',
          'Product_photo_registration': 'Product photo registration',
          'Choose_category': 'Choose a category',
          'enter_color': 'Please enter a color.',
          'enter_keywords': 'Please enter a keyword.',
          'unit_price': 'unit price',
          'enter_product_name': 'Please enter product name(1~40 char)',
          'detail_cut': 'detail cut',
          'image_by_color': 'image by color',
          'representative_image': 'Representative image',
          'advertising_area_R': 'advertising area(R)',
          'total_advertising_cost': 'total advertising cost',
          'purchase_conversion_rate': 'purchase conversion rate',
          'number_of_likes': 'number of likes',
          'ad_cost': 'ad cost',
          'number_of_purchases': 'number of purchases',
          'click_rate': 'click rate',
          'clicks': 'clicks',
          'impressions': 'impressions',
          'advertising_performance': 'advertising performance',
          'Point_usage_history': 'Point usage history',
          'charging': 'charging',
          'Application_history': 'Application history',
          'Advertising_Status': 'Advertising Status',
          'ad_apply': 'Ad Apply',
          'Payment_completion_amount': 'Payment completed amount',
          'Expected_payment_amount': 'Expected payment amount',
          'pay': 'pay',
          'Advertising_R_Application_History': 'Ad R-type application history',
          'Apply': 'Apply',
          '1_day_24': '1-day (24hr)',
          'Ad_Position_Description': 'Ad_Position_Description',
          'register_your_product': 'Please register your product',
          'ad_r': 'Ad type R',
          'ad_impression': 'ad impressions',
          'dingdong_order_price': 'dingdong order amount',
          'order_amount': 'order amount',
          'store_visits': 'store visits',
          'ad_effectiveness_report': 'Advertising effectiveness report',
          'Product_change': 'Change Product',
          'Ad_registration': 'Ad registration',
          'cancel': 'cancel',
          'When_the_daily_budge':
              '- When the daily budget is exhausted, the advertisement is automatically stopped and displayed again the next day. \n\n- In some cases, an over-budget amount may occur.',
          'won': 'won',
          'daily_budget': 'daily budget',
          'remaining_points': 'Remaining Points',
          'ad': 'ad',
          'bulletin': 'bulletin',
          'its_ad': 'It\'s an ad',
          'phone_verification_failed': 'Phone verification failed.',
          'phone_verification_finished': 'Phone verification finished.',
          'sent_verification_number':
              'Verification number was sent to your phone.',
          'home': 'home',
          'orderHistory': 'order History',
          'myPage': 'my Page',
        },
      };
}
