import 'package:get/get.dart';

class uLanguages extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'ko_KR': {
          'enter_verify_code': '인증번호 입력',
          'verify': '인증',
          'ok': '확인',
          'soldout': '품절',
          'liked': '찜',
          'search_2': '검색',
          'winter_outer': '가을 아우터',
          'outer': '아우터몰',
          'submit_review_image': '리뷰 사진 등록',
          'edit_2': '수정',
          'shipping_inquiry': '배송문의',
          'enter_details': '내용을 입력해주세요.',
          'content': '내용',
          'category': '카테고리',
          'Request_new_product': '새로운 제품 요청',
          'return': '반품',
          'top': '상의',
          'Inquiry_title': '문의제목제목',
          // 'do_inquiry': '문의하기',
          'submit': '등록',
          'secret_message': '비밀글',
          'Register_product_inquiry': '상품문의 등록하기',
          'Report': '신고하기',
          'go': '바로가기',
          'total_price': '총 금액',
          'quantity': '수량',
          'select_option': '옵션을 선택해주세요.',
          'option': '옵션',
          'edit': '수정하기',
          // 'pay': '구매하기',
          'inquiry': '문의',
          'More_info': '상세정보',
          'Earn_photo_reviews': '포토리뷰 적립',
          'search': '조회',
          'period': '기간',
          'point': '포인트',
          'my_point': '내 포인트',
          'review': '리뷰',
          'Product_Inquiry': '상품문의',
          'Inquiries': '문의내역',
          'event_marketing_alarm': '이벤트 / 마케팅 / 알림',
          'delete_user_account': '회원탈퇴',
          // 'delete_your_account': '회원탈퇴를 원하십니까?',
          // 'delete_account': '탈퇴',
          'logout': '로그아웃',
          'terms': '이용약관',
          'privacy_policy': '개인정보처리방침',
          'Edit_member_information': '회원정보수정',
          'My_page': '마이페이지',
          'favorite_products': '찜 상품',
          // 'Recently_viewed_products': '최근 본 상품',
          'See_all': '모아보기',
          'order_now_receive_tomorrow': '지금 주문하면 내일 도착',
          'Exhibition_product': '기획전 상품',
          'Exhibition_name': '기획전 이름',
          'Favorites': '즐겨찾기',
          'ranking': '랭킹',
          'store': '스토어',
          'manage': '관리하기',
          'Best_in_store': '우리매장 베스트',
          'view_more': '더보기',
          'dingdong_delivery': '띵동배송',
          'all': '전체',
          'recommended_item': '추천 아이템',
          'dingpick': '띵Pick',
          'Dingdong': '띵동',
          'new': '신상',
          'best': '베스트',
          'home': '홈',
          'Order_Number': '주문번호',
          'View_Details': '상세보기',
          'order_date': '주문일',
          'Delivery_Tracking': '배송조회',
          'purchase_confirmation': '구매확정',
          'Delivery_completed': '배송완료',
          'totall_shipping_fee': '총 배송비',
          // 'total_product_amount': '총 상품 금액',
          'Hyundai_Card_one_time_payment': '현대카드(일시불)',
          'payment_method': '결제수단',
          'Fast_shipping': '빠른배송',
          'contact': '연락처',
          'gift_recipient': '이름',
          'receiver_info': '받는 사람 정보',
          'change': '변경하기',
          'verify_new_password': '새비밀번호 입력 확인',
          'enter_new_password': '새비밀번호 입력',
          'enter_password': '비밀번호 입력',
          'Enter_old_password': '기존 비밀번호 입력',
          'FAQ': '자주 묻는 질문',
          'this_question_content': '질문-내용입니다',
          'question': '질문',
          'etc': '기타',
          'refund': '환불',
          'shipping': '배송',
          'order_history': '주문조회',
          'payment_amount': '결제금액',
          'Same_as_member_info': '회원정보와 동일',
          'shipping_fee': '배송비',
          'Discount_additional_payment': '할인 / 부가결제',
          'order_product': '주문 상품',
          'Payment_info': '결제정보',
          'use': '사용',
          'won': '원',
          'points_available': '사용가능 10원',
          'use_points': '적립금',
          // 'extra_request': '요청사항',
          'phone_number': '휴대폰 번호',
          'buyer_name': '주문하시는 분',
          'delivery_info': '배송정보',
          'payment': '결제',
          'payment_price': '결제 금액',
          'selected_products_num': '선택 상품 개수',
          'Delete all': '전체삭제',
          'Select All': '전체선택',
          'shopping_basket': '장바구니',
          'Update schedule': '업데이트 예정안내',
          'Update_schedule': '업데이트 예정안내',
          'bulletin': '공지사항',
          'day': '일',
          'month': '월',
          'register product': '상품등록',
          'year': '년',
          'birthday': '생일',
          'Address details': '주소 상세',
          'Enter_address': '주소 입력',
          'address': '주소',
          'Zip_code': '우편번호',
          'name': '이름',
          'verify_password': '비밀번호 확인',
          'password': '비밀번호',
          'email': '이메일',
          'id': '아이디',
          'check_available': '중복확인',
          'SignUp': '회원가입',
          'Profile': '회원정보',
          'enter_ID.': '아이디를 입력하세요.',
          'login': '로그인',
          'privacy': '개인정보취급방침',
          'Terms': '이용약관',
          'Terms_of_service': '이용약관 & 개인정보',
          'Confirm_new_password': '새비밀번호 입력 확인',
          'Enter_new_password': '새비밀번호 입력',
          'Change_Password': '비밀번호 변경',
          'Enter_ID': '아이디 입력',
          'cancel': '취소',
          'credit_card_pay': '카드결제',
          'sent_verification_number': '인증번호를 발송했습니다.',
          'phone_verification_failed': '휴대폰 인증 실패. 다시 인증하세요.',
          'phone_verification_finished': '휴대폰 인증이 완료되었습니다.',
        },
        'en_US': {
          'enter_verify_code': 'Enter Verification Code',
          'verify': 'Verify',
          'ok': 'OK',
          'soldout': 'Sold out',
          'liked': 'Liked',
          'search_2': 'Search',
          'winter_outer': 'Winter outer',
          'outer': 'Outer cloth',
          'submit_review_image': 'Submit review image',
          'edit_2': 'edit',
          'shipping_inquiry': 'shipping inquiry',
          'enter_details': 'Please enter contents.',
          'content': 'Content',
          'category': 'category',
          'Request_new_product': 'Request a new product',
          'return': 'return',
          'top': 'top cloth',
          'Inquiry_title': 'Inquiry Subject',
          'do_inquiry': 'Contact us',
          'submit': 'submit',
          'secret_message': 'secret message',
          'Inquiry_content': 'Inquiries',
          'Register_product_inquiry': 'Register product inquiry',
          'Report': 'Report',
          'Write_review': 'Write a review',
          'go': 'go',
          'put_product_in_basket': 'You have added an item to your shopping cart.',
          'total_price': 'total amount',
          'quantity': 'Quantity',
          'select_option': 'Please choose an option.',
          'option': 'option',
          'edit': 'edit',
          'pay': 'Purchase',
          'inquiry': 'inquiry',
          'More_info': 'More information',
          'Earn_photo_reviews': 'Earn photo reviews',
          'search': 'search',
          'period': 'period',
          'point': 'point',
          'my_point': 'my points',
          'review': 'review',
          'Product_Inquiry': 'Product Inquiry',
          'Inquiries': 'Inquiry history',
          'event_marketing_alarm': 'Events / Marketing / Notifications',
          'delete_user_account': 'Account Withdrawal',
          'delete_your_account': 'Do you want to cancel membership?',
          'delete_account': 'delete account',
          'logout': 'log out',
          'terms': 'Terms of service',
          'privacy_policy': 'privacy policy',
          'Edit_member_information': 'Edit member information',
          'My_page': 'my page',
          'favorite_products': 'favorite products',
          'Recently_viewed_products': 'Recently viewed products',
          'See_all': 'See ALL',
          'order_now_receive_tomorrow': 'If you order now, it will arrive tomorrow',
          'Exhibition_product': 'Exhibition product',
          'Exhibition_name': 'Exhibition name',
          'Favorites': 'Favorites',
          'ranking': 'ranking',
          'store': 'store',
          'manage': 'manage',
          'Best_in_store': 'Best in our store',
          'view_more': 'View more',
          'dingdong_delivery': 'Dingdong Shipping',
          'all': 'ALL',
          'recommended_item': 'recommended item',
          'dingpick': 'DING Pick',
          'Dingdong': 'Dingdong',
          'new': 'NEW',
          'best': 'best',
          'home': 'home',
          'Order_Number': 'Order Number',
          'View_Details': 'View Details',
          'order_date': 'order date',
          'Delivery_Tracking': 'Delivery Tracking',
          'purchase_confirmation': 'purchase confirmation',
          'Delivery_completed': 'Delivery completed',
          'totall_shipping_fee': 'total shipping cost',
          'total_product_amount': 'total product amount',
          'Hyundai_Card_one_time_payment': 'Hyundai Card (one-time payment)',
          'payment_method': 'payment method',
          'Fast_shipping': 'Fast shipping',
          'contact': 'contact',
          'gift_recipient': 'gift recipient',
          'receiver_info': 'Recipient information',
          'Order_inquiry_details': 'Order inquiry details',
          'change': 'change',
          'verify_new_password': 'Confirm new password input',
          'enter_new_password': 'Enter new password',
          'enter_password': 'Enter Password',
          'Enter_old_password': 'Enter your old password',
          'FAQ': 'FAQ',
          'this_question_content': 'This is content of the question',
          'question': 'question',
          'etc': 'etc',
          'refund': 'refund',
          'shipping': 'shipping',
          'order_history': 'order inquiry',
          'payment_amount': 'Amount of payment',
          'new_address': 'new shipping address',
          'Same_as_member_info': 'Same as member information',
          'shipping_fee': 'shipping fee',
          'Discount_additional_payment': 'Discount / additional payment',
          'order_product': 'order product',
          'Payment_info': 'Payment information',
          'use': 'use',
          'won': 'won',
          'points_available': '10 won available',
          'use_points': 'Use points',
          'extra_request': 'extra requests',
          'phone_number': 'Phone Number',
          'buyer_name': 'buyer name',
          'delivery_info': 'Shipping Information',
          'payment': 'payment',
          'payment_price': 'Amount of payment',
          'selected_products_num': 'Number of selected products',
          'Delete all': 'Delete all',
          'Select All': 'Select All',
          'shopping_basket': 'shopping basket',
          'Update schedule': 'Update schedule',
          'bulletin': 'announcement',
          'day': 'day',
          'month': 'month',
          'year': 'year',
          'birthday': 'birthday',
          'Address details': 'Address details',
          'Enter_address': 'Enter address',
          'address': 'address',
          'Address Search': 'Address Search',
          'Zip_code': 'Zip code',
          'name': 'name',
          'verify_password': 'verify password',
          'password': 'password',
          'id': 'id',
          'check_available': 'verify',
          'SignUp': 'Sign Up',
          'Profile': 'Profile',
          'singup': 'Sign Up',
          'enter_ID.': 'Please enter your ID.',
          'login': 'login',
          'customer_id_found_successfully': 'Your ID search is complete.',
          'privacy': 'Privacy',
          'Terms': 'Terms of service',
          'Terms_of_service': 'Terms of service',
          'Confirm_new_password': 'Confirm new password input',
          'Enter_new_password': 'Enter new password',
          'Change_Password': 'Change Password',
          'Enter_ID': 'Enter ID',
          'cancel': 'cancel',
          'find_password': 'find password',
          'find_id': 'find ID',
          'credit_card_pay': 'credit card payment',
          'register_product': 'register product'
        },
      };
}
